### ISSUE TITLE
Do you use allways on nvidia card?

### ISSUE THREAD

**Issue by danielpinto8zz6** [MJaoune/ideapad330-config#1]
Thanks so much for sharing this, do you use nvidia card allways on? or some other configuration like optimus-manager?
Thank you

**Comment by MJaoune** [comment]
From what I have heard, I guess it is currently really difficult to make use of both cards at once like on Windows, you need to choose one of them to be always on while the other is off.

If you are a gamer or use graphical intense applications, then Nvidia GPU needs to be always on while Intel's is off, if not, then Intel would be better due to its low power consumption.

**Comment by danielpinto8zz6** [comment]
Thank you so much, 
Does this kernel works 100% for for you?
I have an 15ICH too and have some problems with this kernel

**Comment by MJaoune** [comment]
The only problem I am having is that the kernel is not detecting lid closes and thus the laptop wouldn't get put to sleep when the lid is closed, actually, even the display is not dimmed or turned off when the lid is closed. This I believe is because of weak support of the laptop's ACPI, maybe it can be fixed in later kernel versions.

Other than that, I guess there are no other problems, or at least major ones.

**Comment by danielpinto8zz6** [comment]
I have some wifi errors in dmesg,
Also, will you update it to 5.3.7?
